Repository URECA-TEAM4/gatheru-client, pull requests merged in 2024-09, with the labels that each got.

#8 Main page
  index.html
  src/components/_actions/post_action.js
  src/components/common/Tabs/Tab.js
  src/components/common/ToggleButton/GatherToggleButton.js
  src/components/views/MainPage/MainPage.js
  src/components/views/MainPage/Post.js
  src/components/views/MainPage/PostList.js
Labels: ✨ Feature

#12 feat: detail page
  src/App.js
  src/components/views/DetailPage/DetailPage.js
  src/components/views/MainPage/Post.js
  src/components/views/MainPage/PostList.js
Labels: ✨ Feature

#14 10 feature calendar page db
  package-lock.json
  package.json
  src/components/common/ToggleButton/CalendarToggleButton.js
  src/components/views/CalendarPage/Calendar.js
  src/components/views/CalendarPage/Calendar.module.css
  src/components/views/CalendarPage/CalendarPage.js
Labels: ✨ Feature

#16 Bugfix recruit closure
  src/components/views/CalendarPage/Calendar.js
  src/components/views/MainPage/Post.js
  src/components/views/MainPage/PostList.js
Labels: 🐞 Bug

#15 feature: detail page
  src/components/_actions/post_action.js
  src/components/_actions/types.js
  src/components/_reducers/index.js
  src/components/_reducers/join_reducer.js
  src/components/constants/UserIcon.js
  src/components/views/DetailPage/CommentSection.js
  src/components/views/DetailPage/ContentSection.js
  src/components/views/DetailPage/DeadlineBadge.js
  src/components/views/DetailPage/DetailPage.js
  src/components/views/DetailPage/JoinMogakoButton.js
  src/components/views/DetailPage/JoinStudyContestButton.js
  src/components/views/DetailPage/SingleComment.js
  src/components/views/MainPage/MainPage.js
  src/components/views/MainPage/Post.js
  src/components/views/MainPage/PostList.js
Labels: ✨ Feature

#20 feature: notification
  src/components/_actions/notification_action.js
  src/components/common/Navbar/Navbar.js
  src/components/common/Navbar/Notification.js
  src/components/views/DetailPage/DetailPage.js
  src/components/views/DetailPage/JoinMogakoButton.js
  src/components/views/DetailPage/JoinStudyContestButton.js
Labels: ✨ Feature

#24 fix: no more seconds displayed
  src/components/views/MainPage/Post.js
Labels: 🐞 Bug

#28 fix: study contest time stamp
  src/components/views/MainPage/Post.js
Labels: 🐞 Bug

#30 feat: comment section
  package-lock.json
  package.json
  src/components/views/DetailPage/CommentSection.js
  src/components/views/DetailPage/DetailPage.js
Labels: ✨ Feature

#35 33 feat post update delete
  src/components/_actions/post_action.js
  src/components/_actions/types.js
  src/components/_reducers/index.js
  src/components/_reducers/post_reducer.js
  src/components/views/DetailPage/DetailPage.js
  src/components/views/DetailPage/MogakModal.js
  src/components/views/DetailPage/PostUpdateDelete.js
  src/components/views/DetailPage/StudyContestModal.js
  src/components/views/NewPostPage/NewPostPage.js
Labels: ✨ Feature

#34 docs: Readme
  README.md
  image-1.png
  image.png
Labels: 📄 Docs
